<a href="https://colab.research.google.com/github/subinmun1997/Python-DataAnalysis-and-ImageProcessing/blob/main/NumpyUtilization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

# 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
import numpy as np

# 복수 객체 저장 및 불러오기
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)
# savez 복수개의 numpy 객체를 파일 형태로 저장하고자 할 때 사용
data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']

print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [7]:
import numpy as np

# Numpy 원소 오름차순 정렬
array = np.array([5,9,10,3,1])
print(array)
array.sort()
print(array)

# Numpy 원소 내림차순 정렬
array = np.array([5,9,10,3,1])
print(array)
array.sort()
print(array[::-1]) # 인덱싱 기법을 활용하여 거꾸로 출력

# 각 열을 기준으로 정렬
array = np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)
array.sort(axis=0) # 이때 정렬을 수행함에 있어서 기준을 행으로 삼으면 각각의 열을 봤을 때 더 큰 행이 아래쪽으로 내려오게됨
#즉, 각각의 열을 기준으로 정렬 수행
print(array)

[ 5  9 10  3  1]
[ 1  3  5  9 10]
[ 5  9 10  3  1]
[10  9  5  3  1]
[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [9]:
import numpy as np

# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5) # 0 ~ 10 사이의 5개의 데이터만 출력
print(array)

# 난수의 생성(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3))) # array1의 값을 변경하더라도 array2에는 영향x

# Numpy 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy()
print(array2) 

# 중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
